a = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sodales, mauris at maximus aliquet, felis felis blandit massa, ac tincidunt dolor augue ac sapien. Nam ut quam accumsan, aliquam sapien et, semper nibh. Phasellus nisl ex, sagittis ac tortor et, varius aliquet arcu. Donec non accumsan leo. Nullam a neque tempus, accumsan tellus sed, scelerisque augue. Mauris eget lacus eget lacus molestie rhoncus et a nisi. Quisque accumsan fringilla nunc et tincidunt. Sed a lacus vitae magna congue tristique vel quis ex. Suspendisse potenti. Integer id risus a est aliquet volutpat vitae nec nunc. Sed sed velit nisi. Duis ultricies metus erat, at dapibus lacus tempus sit amet.

Vivamus bibendum sem sed vestibulum rhoncus. Vivamus tincidunt magna lorem. Vivamus vel luctus ante, et commodo risus. Duis ac varius augue, ac elementum felis. Fusce nec orci nisi. Curabitur tempor tincidunt nunc ac porta. Phasellus bibendum eros et enim iaculis, sit amet rhoncus ante vehicula. Mauris a orci eget velit pellentesque auctor in eu tortor. Nunc auctor sit amet risus eget blandit. Duis aliquam urna id mauris semper, eget egestas eros vehicula. Sed tristique justo eget auctor ultricies. Ut accumsan ut magna id hendrerit. Curabitur non dui a velit congue rutrum. Donec lacus ante, eleifend id turpis id, egestas sodales metus.

Fusce vehicula neque at tellus interdum suscipit. Cras vitae ligula rutrum leo elementum lacinia. Sed non faucibus erat. Praesent nec diam eget enim efficitur venenatis. Integer faucibus, diam et tincidunt viverra, leo nisl finibus ante, in porttitor eros dolor in ligula. In vel pharetra felis. Mauris non egestas lectus, vel vehicula erat. Vestibulum dui quam, egestas sit amet ex in, tincidunt mattis turpis. Donec finibus sapien vel est semper varius. Duis diam lectus, ultrices interdum lectus ut, imperdiet aliquet ligula. Aenean fringilla ante ac tristique dictum. Donec eleifend ultricies massa, vel commodo eros convallis quis. Sed quis dui sed justo convallis semper. Proin fermentum odio turpis, in feugiat mauris sodales laoreet. Fusce nec vulputate felis, in posuere mauris. Curabitur dictum tincidunt ipsum, et aliquam arcu luctus ac.

Donec tincidunt ut tellus nec consectetur. Nunc eleifend, eros vel faucibus sollicitudin, magna purus euismod sapien, ac gravida orci arcu eu augue. Etiam commodo lacus sem, et suscipit leo porta quis. Suspendisse potenti. Maecenas sodales sapien vel risus lobortis, vel porta lacus tristique. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vitae fermentum ligula. Mauris a viverra tortor. Quisque vel turpis ante. Aliquam quis nisl in nibh lobortis consequat. Curabitur imperdiet tellus sit amet dictum fringilla. Proin vestibulum purus tempor nisi dapibus condimentum.

Duis eu eleifend lacus. Quisque bibendum eu mi eget pharetra. Pellentesque egestas enim ut purus efficitur suscipit. Morbi porttitor dolor sit amet quam cursus, ut tempor ligula blandit. Pellentesque dictum rutrum ipsum, sed interdum ante condimentum et. Vivamus in leo lacus. Nunc interdum varius dui eu eleifend. Integer bibendum nibh et leo mattis, vel pretium eros bibendum. In convallis, mauris eget egestas dapibus, nisl quam egestas odio, quis vestibulum sem leo id sapien. Proin efficitur fringilla odio. Nunc gravida, dui nec tempus laoreet, nunc nisi ornare dui, et volutpat orci urna vitae metus. Fusce rhoncus scelerisque libero, at iaculis magna. Sed at lectus eget justo pulvinar condimentum. Nullam quis orci feugiat, rutrum quam sit amet, volutpat tellus. Aliquam iaculis maximus convallis."""
print(a)